config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'

  resources :topics do
    resources :bookmarks, only: [:new, :edit, :show]
  end

  root to: 'welcome#index'

  # Incoming Mail From MailGun
  post :incoming, to: 'incoming#create'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new( bookmark_params )
    if @bookmark.save
      flash[:notice] = "Your bookmark has been saved."
      redirect_to @bookmark
    else
      flash[:error] = "Your bookmark could not be created"
      redirect_to bookmarks_new_path
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:topic_id])
    if @bookmark.update_attributes( bookmark_params )
      flash[:notice] = "Bookmark was updated."
    else
      flash[:error] = "Bookmark was not updated."
    end
    redirect_to @bookmark
  end

  def update
    @bookmark = Bookmark.find(params[:topic_id])
    if @bookmark.update_attributes( bookmark_params )
      flash[:notice] = "Bookmark was updated."
      redirect_to @bookmark
    else
      flash[:error] = "Bookmark was not updated."
      render :edit
    end
  end

  def show
    @bookmark = Bookmark.find(parmas[:topic_id])
  end

  def destroy
    @bookmark = Bookmark.find(params[:topic_id])
    if @bookmark.destroy
      flash[:notice] = "Your bookmark has been deleted."
      redirect_to topic_bookmark_path
    else
      flash[:error] = "Your bookmark could not be deleted."
      render :show
    end
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:url, :topic_id)
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def create
    # Find the user by using params[:sender]
    @user = User.find_by(email: params[:sender])
    # Find the topic by using params[:subject]
    @topic = Topic.find_by(title: params[:subject])
    # Assign the url to a variable after retreiving it from params["body-plain"]
    @url = "http://#{params["body-plain"]}"
    # Check if user is nil, if so, create and save a new user
    @user = User.create(email: params[:sender], password: "blocmarks") if @user.nil?
    # Check if the topic is nil, if so, create and save a new topic
    @topic = Topic.create(title: params[:title], user_id: @user.id) if @topic.nil?
    # Now that you're sure you have a valid user and topic, build and save a new bookmark
    @bookmark = Bookmark.create(url: @url, topic_id: @topic.id)
    head 200
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:topic_id])
  end

  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    if @topic.update_attributes( topic_params )
      flash[:notice] = "Topic was updated"
    else
      flash[:error] = "Topic could not be updated at this time"
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :user_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<h1>Bookmarks#edit</h1>
<p>Find me in app/views/bookmarks/edit.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>BLOCMARKS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Blocmarks</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Topics", topics_path %></li>
        <li></li>
      </ul>
      <nav class="nav navbar-nav navbar-right">
        <ul>
        <% if current_user %>
          Welcome back <%= current_user.email %><li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
        </ul>
      </nav>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</nav><!-- /.navbar -->

<% if flash[:notice] %>
   <div class="alert alert-success">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
   </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1 align="center">Blocmark Topics</h1>
<div class="container">
  <div class="row">
    <% @topics.each do |topic| %>
      <div class="col-md-3">
      <%= link_to "##{topic.title}", topic_path %>
      <%= link_to "X", method: :destroy %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1>Topics#show</h1>
<p>Find me in app/views/topics/show.html.erb</p>

app/views/welcome/index.html.erb
<h1>Blocmarks</h1>